### ISSUE TITLE
Change the number of evaluations in the configuration file

### ISSUE THREAD

**Issue by lSkyPassion** [NUS-HPC-AI-Lab/DATM#5]
Dear NUS-HPC-AL-Lab,

I hope this message finds you well. I would like to extend my gratitude for the exceptional work that you and your team have conducted. Recently, I have developed a keen interest in the topic of data distillation and had the opportunity to read your paper on the subject.

While attempting to replicate the experiments detailed in your paper, I encountered a potential issue in the code concerning the evaluation process. Specifically, the configuration file sets num_eval=1 during the distillation process. I am considering modifying this setting to num_eval=5, which would obviate the need to run evaluation.py separately. Instead, I could directly use the maximum accuracy (Max_acc) and standard deviation (Max_std) recorded in wandb to obtain the results reported in your paper.

Could you please confirm if this modification would be appropriate or suggest any alternative approaches if necessary?

Thank you for your attention to this matter, and I look forward to your valuable feedback.

Best regards

**Comment by GzyAftermath** [comment]
You can modify the num_eval to 5 or evaluate the saved dataset 5 times after the distillation.

The latter can reduce the cost.
