### ISSUE TITLE
alpha of buffer

### ISSUE THREAD

**Issue by lSkyPassion** [NUS-HPC-AI-Lab/DATM#6]
Hello, when I was replicating your paper, I wanted to know if training expert trajectories requires training on the same dataset with and without ZCA whitening, and the same applies to distillation, right? My current question is whether I also need to train different expert trajectories based on alpha=0.3 or 1. It seems necessary according to the FTD paper, but buffer_FTD.py does not seem to handle the expert trajectory file paths for different alpha datasets.

**Comment by GzyAftermath** [comment]
According to my experiments, using different alpha seems to have little influence on the distillation performance. If my memory is correct, DATM set it as 0.3 for all cases. You can tune this as FTD suggested, maybe it can further improve the performance.
