### ISSUE TITLE
configs different

### ISSUE THREAD

**Issue by lSkyPassion** [NUS-HPC-AI-Lab/DATM#7]
Hello, while I was reviewing your code, I noticed that the configurations for each dataset and each ipc in the configuration files (configs/xxx/xxx.yaml) seem to differ from those listed in the final parameter table in your paper. 
For example, for CIFAR10, the paper states a batch_syn of 10 for IPC1, but the code specifies 1000, and for IPC10, the paper states 100, but the code specifies 500. Nearly every configuration does not match. 
Additionally, for CIFAR100, the three T values for IPC1 in the paper are 0, 10, and 20, but in the code, they are 0, 20, and 30. 
I also do not understand why there are two opposite values of zca in the same code configuration. Which one is used during training? 
If you have time, could you please answer these three questions so that we can better replicate your results? I would greatly appreciate it.

**Comment by GzyAftermath** [comment]
Sorry for the confusions, have updated the config files.

1. The synthetic dataset of cifar10 ipc1 only contains 10 images, and cifar10 ipc10 only contains 100 images, set batch_syn as a higher value in config won't have an influence.
2. Please refer to the parameters reported in paper.
3. The code will refer to the value of the last zca contained in the config file.

**Comment by lSkyPassion** [comment]
For the third point, I am still not clear. For other MTT series methods, the zca for CIFAR10's IPC50 and CIFAR100's IPC10 is false, but I see that you are all using true. Can I replicate your results by using your configuration?

**Comment by GzyAftermath** [comment]
Yes you can, I haven't tried to do experiments without using zca, all the reported experiments use zca.

**Comment by lSkyPassion** [comment]
ok ，thank u very much

**Comment by lSkyPassion** [comment]
Hello, I just noticed that the data for CIFAR100's IPC1 still seems to be incorrect. The three T values used in the paper are 0, 10, 20, not the three values configured in your code

**Comment by GzyAftermath** [comment]
fixed
